name: Build Android

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  dockcross-android:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    container:
      image: rabits/qt:5.15-android
    strategy:
      matrix:
        include:
          - name: android-arm
            arch: armeabi-v7a
          - name: android-arm64
            arch: arm64-v8a
          - name: android-x86
            arch: x86
          - name: android-x86_64
            arch: x86_64
    steps:
      - name:
        run: git clone https://github.com/openhd/MAVSDK
      - name: disable superbuild on cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "superbuild=-DSUPERBUILD=OFF" >> $GITHUB_ENV && echo "cmake_prefix_path=-DCMAKE_PREFIX_PATH=/work/build/${{ matrix.name }}/third_party/install" >> $GITHUB_ENV
      - name: configure
        run: /bin/bash -c "cmake $superbuild $cmake_prefix_path -DMAVLINK_DIALECT=openhd -DMAVLINK_HEADERS=mavlink-headers -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/${{ matrix.name }}/install -DBUILD_SHARED_LIBS=OFF -DWERROR=OFF -Bbuild/${{ matrix.name }} -H."
      - name: debug
        run: tree
      - name: build
        run: cmake --build build/${{ matrix.name }} -j4 --target install
      - name: package
        run: 7z a mavsdk-android-${{ matrix.name }}.7z build/${{ matrix.name }}/install/
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "MAVSDK-${{ matrix.name }}"
          path: |
            *.7z
     
