name: Build Android

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  dockcross-android:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    container:
      image: rabits/qt:5.15-android
    strategy:
      matrix:
        include:
          - name: android-arm64
            arch: arm64-v8a
    steps:
      - name:
        run: sudo git clone https://github.com/openhd/MAVSDK && cd MAVSDK
      - name: apt update
        run: sudo apt update
      - name: install cmake and build dependencies
        run: sudo apt -y install build-essential cmake git ruby-dev python3-pip cmake curl libjsoncpp-dev libtinyxml2-dev zlib1g libcurl4-gnutls-dev
      - name: configure
        run: sudo cmake -DSUPERBUILD=OFF -DMAVLINK_DIALECT=openhd -DMAVLINK_HEADERS=mavlink-headers -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DWERROR=OFF -H..
      - name: debug
        run: tree
      - name: build
        run: sudo cmake --build build/${{ matrix.name }} -j4 --target install
      - name: package
        run: 7z a mavsdk-android-${{ matrix.name }}.7z build/${{ matrix.name }}/install/
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "MAVSDK-${{ matrix.name }}"
          path: |
            *.7z
     
