name: Build RPI Legacy

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: pguyot/arm-runner-action@v2.3.1 
      id: build_image
      with:
        base_image: https://downloads.raspberrypi.org/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2022-04-07/2022-04-04-raspios-buster-armhf.img.xz
        image_additional_mb: 4000
        copy_repository_path: /opt
        bind_mount_repository: true
        commands: |
            ls -a
            sudo chmod +x install_dep.sh
            sudo ./install_dep.sh
            VER2=$(git rev-parse --short HEAD)
            sudo apt install tree
            mkdir build 
            cd build
            mkdir MAVSDK-package
            sudo gpg --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
            sudo gpg --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
            sudo gpg --export 04EE7237B7D453EC | sudo apt-key add -
            sudo gpg --export 648ACFD622F3D138 | sudo apt-key add -
            echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list.d/backports.list 
            apt update
            apt install -y cmake/buster-backports
            cmake -Bbuild/default -DCMAKE_INSTALL_PREFIX=MAVSDK-package/usr -DCMAKE_BUILD_TYPE=Release -H..
            cmake --build build/default -j4
            sudo cmake --build build/default --target install
            VERSION="2.2.0-evo-$(date '+%m%d%H%M')-${VER2}"
            fpm -a armhf -s dir -t deb -n MAVSDK -v ${VERSION} -C MAVSDK-package
            cp *.deb /opt/
            ls -a

    - name: Debug
      run: ls -a && tree  

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "MAVSDK"
        path: |
          *.deb
          *.log

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
          
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
