name: Windows Debug

on: [push]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  ARTIFACT:     MAVSDK-Windows.zip

jobs:
  build:
    runs-on:  windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/debug/third_party/install
          key: ${{ github.job }}-${{ hashFiles('./third_party/**') }}-2
      - name: install packages
        run: |
            choco install nasm
      - name: configure
        run: cmake -G "Visual Studio 17 2022" -DSUPERBUILD=ON $env:cmake_prefix_path -DCMAKE_BUILD_TYPE=debug -DCMAKE_INSTALL_PREFIX=build/debug/install -DBUILD_MAVSDK_SERVER=ODD -DBUILD_SHARED_LIBS=OFF -DWERROR=OFF -Bbuild/debug -S.
      - name: build
        run: cmake --build build/debug -j2 --config Debug --target install
      - name: Create zip file mavsdk libraries
        run: cd build/debug/install && 7z.exe a -tzip ../../../mavsdk-windows-x64-debug.zip . && cd ../../..
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "MAVSDK"
          path: |
            build/debug/install/*