name: Windows Release test2

on: [push]

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  ARTIFACT:     MAVSDK-Windows.zip

jobs:
  build:
    runs-on:  windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/release/third_party/install
          key: ${{ github.job }}-${{ hashFiles('./third_party/**') }}-2
      - name: disable superbuild on cache hit
        run: |
            echo "superbuild=-DSUPERBUILD=OFF" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "cmake_prefix_path=-DCMAKE_PREFIX_PATH=$(pwd)/build/release/third_party/install"
      - name: install packages
        run: |
            choco install nasm
      - name: configure
        run: cmake -G "Visual Studio 17 2022" -DSUPERBUILD=OFF $env:cmake_prefix_path -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=build/release/install -DBUILD_MAVSDK_SERVER=ODD -DBUILD_SHARED_LIBS=OFF -DWERROR=OFF -Bbuild/release -S.
      - name: build
        run: cmake --build build/release -j2 --config Release --target install
      - name: Create zip file mavsdk libraries
        run: cd build/release/install && 7z.exe a -tzip ../../../mavsdk-windows-x64-release.zip . && cd ../../..
      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "MAVSDK"
          path: |
            *.zip
            *.exe